# Generated by Django 5.0.6 on 2024-07-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("share_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shares_available", models.IntegerField()),
                ("controlling_stake", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "deal_date",
                    models.DateField(
                        auto_now_add=True, primary_key=True, serialize=False
                    ),
                ),
                ("shares_quantity", models.IntegerField()),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_exchange.buyer",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_exchange.company",
                    ),
                ),
            ],
        ),
    ]
