# Generated by Django 5.0.6 on 2024-07-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_exchange", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="deal_date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
