# Generated by Django 5.0.6 on 2024-07-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_exchange", "0002_alter_deal_deal_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buyer",
            old_name="full_name",
            new_name="name",
        ),
    ]
